---
- name: Install Repository Key
  become: yes
  apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  when: (ansible_distribution == "Ubuntu")
  tags:
      - logstash

- name: Install Repository
  become: yes
  apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/{{ elastic_stack_version }}/apt stable main"
      state: present
  when: (ansible_distribution == "Ubuntu")
  tags:
      - logstash

- name: Install Repository
  become: yes
  yum_repository:
      name: "elastic-{{ elastic_stack_version }}"
      description: Elastic Package Repository
      baseurl: "https://artifacts.elastic.co/packages/{{ elastic_stack_version }}/yum"
      gpgcheck: yes
      gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      state: present
  when: (ansible_distribution == "RedHat")
  tags:
      - logstash

# Don't bother fighting it -- Logstash wants Java in a particular spot
- name: Soft-link java executable
  become: yes
  file:
      src: "{{ jdk_global_jdk_directory }}/bin/java"
      dest: "/usr/bin/java"
      state: link
  when: elastic_logstash_install
  tags:
      - logstash

- name: Install Logstash
  become: yes
  apt:
      name: logstash
      update_cache: yes
      state: present
      allow_unauthenticated: yes
  when: (ansible_distribution == "Ubuntu") and (elastic_logstash_install)
  tags:
      - logstash

- name: Install Logstash
  become: yes
  yum:
        name: logstash
        state: present
        update_cache: yes
  when: (ansible_distribution == "RedHat") and (elastic_logstash_install)
  tags:
      - logstash

# To test this, you can issue from a remote machine: logger --server 192.168.1.78 --port 5514 --priority 0  --tag test 'Hello, World!'
- name: Install Syslog Logstash Configuration
  become: yes
  template:
      src: templates/syslog-to-elasticsearch.conf.j2
      dest: /etc/logstash/conf.d/syslog-to-elasticsearch.conf
      mode: 0644
      backup: yes
  when: elastic_logstash_install
  tags:
      - logstash

# To test do: echo '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | gzip | nc -u -w 1 192.168.1.78 12201
- name: Install GELF Logstash Configuration
  become: yes
  template:
      src: templates/gelf-to-elasticsearch.conf.j2
      dest: /etc/logstash/conf.d/gelf-to-elasticsearch.conf
      mode: 0644
      backup: yes
  when: elastic_logstash_install
  tags:
      - logstash

- name: Install Heartbeat Logstash Configuration
  become: yes
  template:
      src: templates/heartbeat-to-elasticsearch.conf.j2
      dest: /etc/logstash/conf.d/heartbeat-to-elasticsearch.conf
      mode: 0644
      backup: yes
  when: elastic_logstash_install
  tags:
      - logstash

- name: Enable Logstash
  become: yes
  shell: systemctl daemon-reload && systemctl enable logstash.service
  when: elastic_logstash_install
  tags:
      - logstash

- name: Start Logstash
  become: yes
  command: systemctl restart logstash.service
  when: elastic_logstash_install
  tags:
      - logstash
